const STRENGTH = 'strength';
const STRENGTH_ABBREVIATION = 'str';
const DEXTERITY = 'dexterity';
const DEXTERITY_ABBREVIATION = 'dex';
const CONSTITUTION = 'constitution';
const CONSTITUTION_ABBREVIATION = 'con';
const INTELLIGENCE = 'intelligence';
const INTELLIGENCE_ABBREVIATION = 'int';
const WISDOM = 'wisdom';
const WISDOM_ABBREVIATION = 'wis';
const CHARISMA = 'charisma';
const CHARISMA_ABBREVIATION = 'cha';

module.exports = {
	STRENGTH,
	STRENGTH_ABBREVIATION,
	DEXTERITY,
	DEXTERITY_ABBREVIATION,
	CONSTITUTION,
	CONSTITUTION_ABBREVIATION,
	INTELLIGENCE,
	INTELLIGENCE_ABBREVIATION,
	WISDOM,
	WISDOM_ABBREVIATION,
	CHARISMA,
	CHARISMA_ABBREVIATION
};
