const STRENGTH = 'strength';
const STRENGTH_ABBREVIATION = 'str';
const DEXTERITY = 'dexterity';
const DEXTERITY_ABBREVIATION = 'dex';
const CONSTITUTION = 'constitution';
const CONSTITUTION_ABBREVIATION = 'con';
const INTELLIGENCE = 'intelligence';
const INTELLIGENCE_ABBREVIATION = 'int';
const WISDOM = 'wisdom';
const WISDOM_ABBREVIATION = 'wis';
const CHARISMA = 'charisma';
const CHARISMA_ABBREVIATION = 'cha';

module.exports = {
	STRENGTH: STRENGTH,
	STRENGTH_ABBREVIATION: STRENGTH_ABBREVIATION,
	DEXTERITY: DEXTERITY,
	DEXTERITY_ABBREVIATION: DEXTERITY_ABBREVIATION,
	CONSTITUTION: CONSTITUTION,
	CONSTITUTION_ABBREVIATION: CONSTITUTION_ABBREVIATION,
	INTELLIGENCE: INTELLIGENCE,
	INTELLIGENCE_ABBREVIATION: INTELLIGENCE_ABBREVIATION,
	WISDOM: WISDOM,
	WISDOM_ABBREVIATION: WISDOM_ABBREVIATION,
	CHARISMA: CHARISMA,
	CHARISMA_ABBREVIATION: CHARISMA_ABBREVIATION
}
